name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install pyinstaller psutil
      - name: Build binary
        run: pyinstaller --onefile PYfetch.py
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/PYfetch